openapi: 3.0.3
info:
  title: Sample API
  version: 1.0.0
paths:
  /hello:
    get:
      operationId: hello
      summary: Returns a greeting
      responses:
        '200':
          description: A JSON object with a greeting message.
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string

  /testauth:
    get:
      operationId: testauth
      summary: Get test if I logged
      description: Returns string test if user logged.
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successfully retrieved user information.
          content:
            application/json:
              schema:
                type: object
                properties:
                  sub:
                    type: string
                    description: Auth0 user ID.
                    example: auth0|1234567890
                  login:
                    type: string
                    example: johnd
        '401':
          description: Unauthorized, missing or invalid token.
        '500':
          description: Server error while retrieving user information.

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
